### ISSUE TITLE
Updating a date property fails on the validation

### ISSUE THREAD

**Issue by pihomeserver** [adam-cowley/neode#102]
Hello
First thanks for the project !

I have a basic book node model : 
```
module.exports = {
  ISBN: {
    type: 'int',
    primary: true
  },
  title: {
    type: 'string'
  },
  author: {
    type: 'string'
  },
  publication: {
    type: 'date'
  },
  createdAt: {
    type: 'datetime',
    default: () => new Date()
  }
}
```
I would like to update the publication property a specific book via API like this : 
```
  neo4j.first('Books', 'ISBN', parseInt(req.body.ISBN)).then( book => {
    if (!book) throw({ status: 'error', message: 'Missing or wrong required fields'});
		return book.update({
      title: req.body.title,
      author: req.body.author,
      publication: new Date(req.body.publication),
		})
	})
	.then( book => {
		return res.status(200).json({ status: 'success', message: 'Book updated', data: {book: book.properties()} });
	})
	.catch((err) => { console.log(err) ; next(err) })
```
I got in the catch the following error
```
ValidationError: ERROR_VALIDATION
    at /home/chris/bookApp/node_modules/neode/build/Services/Validator.js:297:23
    at internals.Object._validateWithOptions (/home/chris/bookApp/node_modules/@hapi/joi/lib/types/any/index.js:766:20)
    at module.exports.internals.Any.root.validate (/home/chris/bookApp/node_modules/@hapi/joi/lib/index.js:145:23)
    at /home/chris/bookApp/node_modules/neode/build/Services/Validator.js:295:21
    at new Promise (<anonymous>)
    at Validator (/home/chris/bookApp/node_modules/neode/build/Services/Validator.js:294:10)
    at UpdateNode (/home/chris/bookApp/node_modules/neode/build/Services/UpdateNode.js:14:36)
    at Node.update (/home/chris/bookApp/node_modules/neode/build/Node.js:280:41)
    at /home/chris/bookApp/api/books/books.controller.js:173:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  details: [
    {
      message: '"publication" must be an instance of "Date"',
      path: [Array],
      type: 'object.type',
      context: [Object]
    }
  ],
  input: {
    title: 'new title',
    author: 'new author',
    publication: 2020-01-01T00:00:00.000Z
  },
  _joiError: Error [ValidationError]: child "publication" fails because ["publication" must be an instance of "Date"]
....
```
As you can see the date seems to be correct but i can't get what the error could be
I tried the type datetime and then i have an error about publication not being an instance of Object

Any advice is welcome

**Comment by adam-cowley** [comment]
Which version of neode are you using?

**Comment by pihomeserver** [comment]
Here is my package.json content : `"neode": "^0.4.2"`

**Comment by adam-cowley** [comment]
Great catch, the properties weren't being cleaned so it expected an instance of neo4j's DateTime rather than a native javascript date - I've just published 0.4.3 which should fix this for you.  Let me know if it works

**Comment by adam-cowley** [comment]
I've just tested with this and everything seems fine

```js
// Define a Neode Instance
const neode = require("neode")
    .fromEnv()
    .with({
        Book: {
            ISBN: {
                type: 'int',
                primary: true
            },
            title: {
                type: 'string'
            },
            author: {
                type: 'string'
            },
            publication: {
                type: 'date'
            },
            createdAt: {
                type: 'datetime',
                default: () => new Date()
            }
        }
    });

neode.create('Book', { 'ISBN': 1 })
    .then(book => book.update({ publication: new Date() }))
    .then(book => console.log(book.properties()))
    .catch(e => console.error(e.details))
```

**Comment by pihomeserver** [comment]
Same issue : 
```
updateByISBN = (req, res, next) => {
  neo4j.create('Books', { 'ISBN': 1 })
  .then(book => book.update({ publication: new Date() }))
  .then(book => console.log(book.properties()))
  .catch(e => console.error(e.details))
  res.status(200).json({ status: 'success', message: 'Book updated'})
```
Output : 
```
[
  {
    message: '"publication" must be an instance of "Date"',
    path: [ 'publication' ],
    type: 'object.type',
    context: {
      type: 'Date',
      value: 2020-03-13T14:11:44.104Z,
      key: 'publication',
      label: 'publication'
    }
  }
]
```

**Comment by adam-cowley** [comment]
Has the version definitely updated?  Try `npm i --save neode@^0.4.3`

I've just run this code and get the output at the bottom:

https://gist.github.com/adam-cowley/a5995e72438095b06dec03eddfbd47c1

**Comment by pihomeserver** [comment]
My full apologizes i did not understood the upgrade requirement. 
Now it works ! Thank you
