### ISSUE TITLE
Issue creating nodes

### ISSUE THREAD

**Issue by taylor009** [adam-cowley/neode#115]
I'm trying to create a node but from a request but I get an error in regards to .toLowerCase of undefined 

here is my function code:

`exports.createUser = async(req, res) => {
    const { email, password, first_name, last_name } = req.body;

    try {
        await neode.create('User', {
            email: email,
            password: password,
            first_name: first_name,
            last_name: last_name
        }).then(results => {
            res.status(201).json({
                message: "User created successfully"
            })
        })
    }
    catch (err) {
        console.log(err)
    }
};`

**Comment by adam-cowley** [comment]
Could you paste the entire stack trace please?

**Comment by taylor009** [comment]
@adam-cowley here is stack trace:

TypeError: Cannot read property 'toLowerCase' of undefined
    at CleanValue (/home/taylor/duw/api/node_modules/neode/build/Services/CleanValue.js:24:36)
    at /home/taylor/duw/api/node_modules/neode/build/Services/GenerateDefaultValues.js:45:48
    at Array.forEach (<anonymous>)
    at GenerateDefaultValuesAsync (/home/taylor/duw/api/node_modules/neode/build/Services/GenerateDefaultValues.js:25:23)
    at GenerateDefaultValues (/home/taylor/duw/api/node_modules/neode/build/Services/GenerateDefaultValues.js:61:16)
    at Create (/home/taylor/duw/api/node_modules/neode/build/Services/Create.js:27:48)
    at Model.create (/home/taylor/duw/api/node_modules/neode/build/Queryable.js:65:37)
    at Neode.create (/home/taylor/duw/api/node_modules/neode/build/index.js:205:37)
    at _callee$ (/home/taylor/duw/api/src/controllers/user.js:22:21)
    at tryCatch (/home/taylor/duw/api/node_modules/regenerator-runtime/runtime.js:45:40)

**Comment by adam-cowley** [comment]
It looks like there's something wrong with the configuration of a property type.  Can I take a look at your User.js file?  

https://github.com/adam-cowley/neode/blob/master/build/Services/CleanValue.js#L24

**Comment by taylor009** [comment]
yeah here it is @adam-cowley 

`
module.exports = { 
  labels: ['User'],
  id: { 
    type: 'uuid',
    primary: true 
  },
  first_name: String,
  last_name: String,
  email: String,
  password: String 
};
`

I can give you access to the repo if you would like to investigate further.

**Comment by adam-cowley** [comment]
Ahhh...the type is a string:

```
module.exports = { 
  labels: ['User'], 
  id: { type: 'uuid', primary: true }, 
  first_name: 'string', 
  last_name: 'string', 
  email: {type: 'string', unique: true },
  password: 'string' 
};
```

I need to do a better job of validating these schemas when neode loads them
