### ISSUE TITLE
Invalid input '.': expected whitespace, comment, a property key name, '}', an

### ISSUE THREAD

**Issue by raphaelLacerda** [adam-cowley/neode#36]
I've tried to run node/example/index.js and got the follow exception

Any ideas?

Neo4jError: Invalid input '.': expected whitespace, comment, a property key name, '}', an identifier or UnsignedDecimalInteger (line 7, column 9 (offset: 128))
"        .*"
         ^

    at captureStacktrace (/Users/lacerdaph/IdeaProjects/bb/kernel-label/node_modules/neode/node_modules/neo4j-driver/lib/v1/result.js:200:15)
    at new Result (/Users/lacerdaph/IdeaProjects/bb/kernel-label/node_modules/neode/node_modules/neo4j-driver/lib/v1/result.js:73:19)
    at Session._run (/Users/lacerdaph/IdeaProjects/bb/kernel-label/node_modules/neode/node_modules/neo4j-driver/lib/v1/session.js:116:14)
    at Session.run (/Users/lacerdaph/IdeaProjects/bb/kernel-label/node_modules/neode/node_modules/neo4j-driver/lib/v1/session.js:95:19)
    at Neode.cypher (/Users/lacerdaph/IdeaProjects/bb/kernel-label/node_modules/neode/build/index.js:328:28)
    at Neode.writeCypher (/Users/lacerdaph/IdeaProjects/bb/kernel-label/node_modules/neode/build/index.js:306:25)
    at Builder.execute (/Users/lacerdaph/IdeaProjects/bb/kernel-label/node_modules/neode/build/Query/Builder.js:706:40)
    at /Users/lacerdaph/IdeaProjects/bb/kernel-label/node_modules/neode/build/Services/Create.js:39:39
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:3244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by adam-cowley** [comment]
I've just tried running this and I get the expected output. What version of Node are you running?  Do you have any loaders registered for es6?  You can also try the Example repository at https://github.com/adam-cowley/neode-example
