### ISSUE TITLE
Unable to `find` model

### ISSUE THREAD

**Issue by am17torres** [adam-cowley/neode#94]
When trying to run the `instance.model(label).find(id)` command I get an error with the following stacktrace:

```
// attempt to get by Organization by id passed via param
const response = await instance.model('Organization').find(id)

// error
Neo4jError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 3, column 18 (offset: 43))
"WHERE (this.id = {where_this_id})"
                  ^

    at captureStacktrace (~/node_modules/neode/node_modules/neo4j-driver/lib/v1/result.js:199:15)
    at new Result (~/node_modules/neode/node_modules/neo4j-driver/lib/v1/result.js:65:19)
    at Session._run (~/node_modules/neode/node_modules/neo4j-driver/lib/v1/session.js:152:14)
    at Session.run (~/node_modules/neode/node_modules/neo4j-driver/lib/v1/session.js:130:19)
    at Neode.cypher (~/node_modules/neode/build/index.js:346:28)
    at Builder.execute (~/node_modules/neode/build/Query/Builder.js:807:40)
    at First (~/node_modules/neode/build/Services/First.js:40:44)
    at Model.first (~/node_modules/neode/build/Queryable.js:185:40)
    at Model.find (~/node_modules/neode/build/Queryable.js:156:25)
    at Function.getOrganization (~/src/api-v1/services/OrganizationsService.js:27:37) {
  code: 'Neo.ClientError.Statement.SyntaxError',
  name: 'Neo4jError',
  query: 'MATCH\n' +
    '(this:Organization)\n' +
    'WHERE (this.id = {where_this_id}) \n' +
    'RETURN\n' +
    '\n' +
    '     this { \n' +
    '        .*\n' +
    '        ,__EAGER_ID__: id(this)\n' +
    '        ,__EAGER_LABELS__: labels(this)\n' +
    '    }\n' +
    'LIMIT 1',
  params: { where_this_id: 'MNsEM70e' }
```

Is this something that needs to be corrected in this module or is this a problem with a dependency?

**Comment by am17torres** [comment]
I also cloned the repo and ran the tests and many of them fail due to this error. I'm trying to find out how the query is built to see if a PR is simple in scope.

**Comment by adam-cowley** [comment]
I've just pushed version 0.3.7 with your PR merged.  Thank you for your contribution!
